//
//  TextureManager.h
//  GMaps3D
//
//  Created by Igor Rendulic on 5/6/13.
//  Copyright (c) 2013 Igor Rendulic. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "Singleton.h"

typedef enum {
    TEXTURE_HQ,
    TEXTURE_BARRACK,
    TEXTURE_BARRACK_ATTACKED,
    TEXTURE_ENEMY_TERRAIN_0,
    TEXTURE_ENEMY_TERRAIN_1,
    TEXTURE_ENEMY_TERRAIN_2,
    TEXTURE_ENEMY_TERRAIN_3,
    TEXTURE_ENEMY_TERRAIN_4,
    TEXTURE_ENEMY_TERRAIN_5,
    TEXTURE_ENEMY_TERRAIN_6,
    TEXTURE_ENEMY_TERRAIN_7,
    TEXTURE_ENEMY_TERRAIN_8,
    TEXTURE_ENEMY_TERRAIN_9,
    TEXTURE_ENEMY_TERRAIN_ATTACKED,
    TEXTURE_ENEMY_TERRAIN_BARRACK_ATTACKED,
    TEXTURE_ENEMY_TERRAIN_BARRACK,
    TEXTURE_ENEMY_TERRAIN_HQ_ATTACKED,
    TEXTURE_ENEMY_TERRAIN_HQ,
    TEXTURE_ENEMY_TERRAIN_KNIGHT_ATTACKED,
    TEXTURE_ENEMY_TERRAIN_KNIGHT_EMPTY_MOVING,
    TEXTURE_ENEMY_TERRAIN_KNIGHT_EMPTY,
    TEXTURE_ENEMY_TERRAIN_KNIGHT_MOVING,
    TEXTURE_ENEMY_TERRAIN_KNIGHT,
    TEXTURE_ENEMY_TERRAIN_SETTLER_MOVING,
    TEXTURE_ENEMY_TERRAIN_SETTLER,
    TEXTURE_ENEMY_TERRAIN_SPY,
    TEXTURE_ENEMY_TERRAIN,
    TEXTURE_HQ_ATTACKED,
    TEXTURE_KNIGHT_EMPTY_TERRAIN_MOVING,
    TEXTURE_KNIGHT_EMPTY_TERRAIN,
    TEXTURE_KNIGHT_MY_TERRAIN_MOVING,
    TEXTURE_KNIGHT_MY_TERRAIN,
    TEXTURE_MY_TERRAIN_0_ATTACKED,
    TEXTURE_MY_TERRAIN_0,
    TEXTURE_MY_TERRAIN_1_ATTACKED,
    TEXTURE_MY_TERRAIN_1,
    TEXTURE_MY_TERRAIN_2_ATTACKED,
    TEXTURE_MY_TERRAIN_2,
    TEXTURE_MY_TERRAIN_3_ATTACKED,
    TEXTURE_MY_TERRAIN_3,
    TEXTURE_MY_TERRAIN_4_ATTACKED,
    TEXTURE_MY_TERRAIN_4,
    TEXTURE_MY_TERRAIN_5_ATTACKED,
    TEXTURE_MY_TERRAIN_5,
    TEXTURE_MY_TERRAIN_6_ATTACKED,
    TEXTURE_MY_TERRAIN_6,
    TEXTURE_MY_TERRAIN_7_ATTACKED,
    TEXTURE_MY_TERRAIN_7,
    TEXTURE_MY_TERRAIN_8_ATTACKED,
    TEXTURE_MY_TERRAIN_8,
    TEXTURE_MY_TERRAIN_9_ATTACKED,
    TEXTURE_MY_TERRAIN_9,
    TEXTURE_MY_TERRAIN_10_ATTACKED,
    TEXTURE_MY_TERRAIN_10,
    TEXTURE_SETTLER_MOVING,
    TEXTURE_SETTLER,
    TEXTURE_SPY_ATTACKED,
    TEXTURE_SPY,
    TEXTURE_KNIGHT_EMPTY_TERRAIN_ATTACKED,
    TEXTURE_POWER_1,
    TEXTURE_POWER_2,
    TEXTURE_POWER_3,
    TEXTURE_POWER_4,
    TEXTURE_POWER_5,
    TEXTURE_POWER_6,
    TEXTURE_POWER_7,
    TEXTURE_POWER_8,
    TEXTURE_POWER_9,
    TEXTURE_POWER_0,
    TEXTURE_SHIELD,
    TEXTURE_TERRAIN_BATTERING_RAM
} TextureType;


@interface TextureManager : NSObject

+(TextureManager *)sharedTextureManager;

- (GLuint) getTexture:(int)textureIndex;

@end
